import React, { Fragment } from 'react';
import { Infocard } from '../components/Infocard';
import s from '../styles/app.style';
import '../styles.css';

export const Dashboard = props => (
  <div>
    <h1>Dashboard Page</h1>
    <Infocard>Look a card!</Infocard>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pellentesque mollis urna, vel hendrerit nisi convallis eu. Maecenas nec urna id ligula ornare gravida non sed leo. In sit amet egestas ligula. Cras et posuere felis. Quisque metus nulla, facilisis sit amet tincidunt ac, suscipit nec ipsum. Sed vestibulum purus nisi, a blandit velit laoreet eu. Nullam volutpat dui sed nulla molestie aliquet. Nunc eleifend ut lacus id pharetra. Mauris maximus tortor sed nulla rhoncus scelerisque. Praesent dignissim purus in tincidunt convallis. Nullam convallis augue in ante bibendum, quis euismod felis sodales. Vestibulum turpis nulla, mattis ac mauris sed, pellentesque aliquet elit. Sed ornare aliquet massa, et semper magna semper vel.

Fusce nec felis ac ante iaculis tincidunt. Mauris interdum augue nec pharetra maximus. Pellentesque vel aliquam leo. Donec in ipsum eu orci facilisis gravida. Nullam consectetur lectus ut lobortis facilisis. Aenean at pharetra lorem. In luctus ante tortor, ut condimentum ipsum malesuada ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt, erat vitae mollis elementum, tellus sapien cursus diam, et dignissim magna velit eget mi. Nam leo justo, semper in quam id, ullamcorper dictum massa.

Donec consequat tempor suscipit. Aliquam convallis eros vehicula, volutpat risus eget, porta massa. Suspendisse potenti. Mauris finibus pellentesque purus, eu efficitur tortor accumsan bibendum. Phasellus rutrum, dolor ac cursus aliquet, velit velit blandit augue, ut sodales odio orci eu magna. Praesent malesuada malesuada leo, quis semper lorem pellentesque a. Aliquam erat volutpat. In mattis turpis non nisi congue iaculis. Sed fermentum ligula eu faucibus gravida. Nulla facilisi. Aenean porta accumsan sapien, vitae imperdiet orci vulputate in. Quisque ac sapien lorem. Cras risus libero, elementum ac quam nec, eleifend interdum massa. Duis pellentesque ullamcorper vehicula. Pellentesque justo quam, faucibus a felis id, commodo faucibus sem.

Vivamus ante nulla, maximus sed finibus ac, mollis nec diam. Quisque placerat enim ante, vel ullamcorper risus tempus at. Etiam quis est sed erat rutrum lobortis. Aliquam eu varius mauris. Cras ac convallis purus. Praesent sit amet leo vitae lorem fringilla sodales. Proin sit amet nunc feugiat, iaculis est sed, molestie arcu. Maecenas feugiat urna sit amet tincidunt scelerisque. Pellentesque ultricies erat sed turpis congue, vel porta massa sagittis. Vivamus non accumsan odio. Vivamus ipsum dui, luctus id mauris vitae, semper pellentesque tortor. Aliquam erat volutpat. Proin vitae auctor mauris. Donec dapibus odio euismod, dignissim nisl nec, tristique dui.

Fusce nec sapien quis nibh lobortis lobortis at vitae nulla. Sed mollis mauris in lacus porttitor elementum sed nec orci. Mauris quis dolor at ex placerat placerat. Vivamus tincidunt sagittis turpis. Ut a sapien at purus aliquet vestibulum vitae eu ante. In hac habitasse platea dictumst. Ut bibendum tortor porta, posuere felis eget, ultricies magna. In et libero nec lacus dignissim mollis eget a lorem. Pellentesque quis condimentum mi. Ut at risus ipsum. Pellentesque ac mi odio. In sed magna placerat, suscipit est in, fermentum metus. Curabitur in diam ac ligula iaculis condimentum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pellentesque mollis urna, vel hendrerit nisi convallis eu. Maecenas nec urna id ligula ornare gravida non sed leo. In sit amet egestas ligula. Cras et posuere felis. Quisque metus nulla, facilisis sit amet tincidunt ac, suscipit nec ipsum. Sed vestibulum purus nisi, a blandit velit laoreet eu. Nullam volutpat dui sed nulla molestie aliquet. Nunc eleifend ut lacus id pharetra. Mauris maximus tortor sed nulla rhoncus scelerisque. Praesent dignissim purus in tincidunt convallis. Nullam convallis augue in ante bibendum, quis euismod felis sodales. Vestibulum turpis nulla, mattis ac mauris sed, pellentesque aliquet elit. Sed ornare aliquet massa, et semper magna semper vel.

Fusce nec felis ac ante iaculis tincidunt. Mauris interdum augue nec pharetra maximus. Pellentesque vel aliquam leo. Donec in ipsum eu orci facilisis gravida. Nullam consectetur lectus ut lobortis facilisis. Aenean at pharetra lorem. In luctus ante tortor, ut condimentum ipsum malesuada ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt, erat vitae mollis elementum, tellus sapien cursus diam, et dignissim magna velit eget mi. Nam leo justo, semper in quam id, ullamcorper dictum massa.

Donec consequat tempor suscipit. Aliquam convallis eros vehicula, volutpat risus eget, porta massa. Suspendisse potenti. Mauris finibus pellentesque purus, eu efficitur tortor accumsan bibendum. Phasellus rutrum, dolor ac cursus aliquet, velit velit blandit augue, ut sodales odio orci eu magna. Praesent malesuada malesuada leo, quis semper lorem pellentesque a. Aliquam erat volutpat. In mattis turpis non nisi congue iaculis. Sed fermentum ligula eu faucibus gravida. Nulla facilisi. Aenean porta accumsan sapien, vitae imperdiet orci vulputate in. Quisque ac sapien lorem. Cras risus libero, elementum ac quam nec, eleifend interdum massa. Duis pellentesque ullamcorper vehicula. Pellentesque justo quam, faucibus a felis id, commodo faucibus sem.

Vivamus ante nulla, maximus sed finibus ac, mollis nec diam. Quisque placerat enim ante, vel ullamcorper risus tempus at. Etiam quis est sed erat rutrum lobortis. Aliquam eu varius mauris. Cras ac convallis purus. Praesent sit amet leo vitae lorem fringilla sodales. Proin sit amet nunc feugiat, iaculis est sed, molestie arcu. Maecenas feugiat urna sit amet tincidunt scelerisque. Pellentesque ultricies erat sed turpis congue, vel porta massa sagittis. Vivamus non accumsan odio. Vivamus ipsum dui, luctus id mauris vitae, semper pellentesque tortor. Aliquam erat volutpat. Proin vitae auctor mauris. Donec dapibus odio euismod, dignissim nisl nec, tristique dui.

Fusce nec sapien quis nibh lobortis lobortis at vitae nulla. Sed mollis mauris in lacus porttitor elementum sed nec orci. Mauris quis dolor at ex placerat placerat. Vivamus tincidunt sagittis turpis. Ut a sapien at purus aliquet vestibulum vitae eu ante. In hac habitasse platea dictumst. Ut bibendum tortor porta, posuere felis eget, ultricies magna. In et libero nec lacus dignissim mollis eget a lorem. Pellentesque quis condimentum mi. Ut at risus ipsum. Pellentesque ac mi odio. In sed magna placerat, suscipit est in, fermentum metus. Curabitur in diam ac ligula iaculis condimentum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pellentesque mollis urna, vel hendrerit nisi convallis eu. Maecenas nec urna id ligula ornare gravida non sed leo. In sit amet egestas ligula. Cras et posuere felis. Quisque metus nulla, facilisis sit amet tincidunt ac, suscipit nec ipsum. Sed vestibulum purus nisi, a blandit velit laoreet eu. Nullam volutpat dui sed nulla molestie aliquet. Nunc eleifend ut lacus id pharetra. Mauris maximus tortor sed nulla rhoncus scelerisque. Praesent dignissim purus in tincidunt convallis. Nullam convallis augue in ante bibendum, quis euismod felis sodales. Vestibulum turpis nulla, mattis ac mauris sed, pellentesque aliquet elit. Sed ornare aliquet massa, et semper magna semper vel.

Fusce nec felis ac ante iaculis tincidunt. Mauris interdum augue nec pharetra maximus. Pellentesque vel aliquam leo. Donec in ipsum eu orci facilisis gravida. Nullam consectetur lectus ut lobortis facilisis. Aenean at pharetra lorem. In luctus ante tortor, ut condimentum ipsum malesuada ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt, erat vitae mollis elementum, tellus sapien cursus diam, et dignissim magna velit eget mi. Nam leo justo, semper in quam id, ullamcorper dictum massa.

Donec consequat tempor suscipit. Aliquam convallis eros vehicula, volutpat risus eget, porta massa. Suspendisse potenti. Mauris finibus pellentesque purus, eu efficitur tortor accumsan bibendum. Phasellus rutrum, dolor ac cursus aliquet, velit velit blandit augue, ut sodales odio orci eu magna. Praesent malesuada malesuada leo, quis semper lorem pellentesque a. Aliquam erat volutpat. In mattis turpis non nisi congue iaculis. Sed fermentum ligula eu faucibus gravida. Nulla facilisi. Aenean porta accumsan sapien, vitae imperdiet orci vulputate in. Quisque ac sapien lorem. Cras risus libero, elementum ac quam nec, eleifend interdum massa. Duis pellentesque ullamcorper vehicula. Pellentesque justo quam, faucibus a felis id, commodo faucibus sem.

Vivamus ante nulla, maximus sed finibus ac, mollis nec diam. Quisque placerat enim ante, vel ullamcorper risus tempus at. Etiam quis est sed erat rutrum lobortis. Aliquam eu varius mauris. Cras ac convallis purus. Praesent sit amet leo vitae lorem fringilla sodales. Proin sit amet nunc feugiat, iaculis est sed, molestie arcu. Maecenas feugiat urna sit amet tincidunt scelerisque. Pellentesque ultricies erat sed turpis congue, vel porta massa sagittis. Vivamus non accumsan odio. Vivamus ipsum dui, luctus id mauris vitae, semper pellentesque tortor. Aliquam erat volutpat. Proin vitae auctor mauris. Donec dapibus odio euismod, dignissim nisl nec, tristique dui.

Fusce nec sapien quis nibh lobortis lobortis at vitae nulla. Sed mollis mauris in lacus porttitor elementum sed nec orci. Mauris quis dolor at ex placerat placerat. Vivamus tincidunt sagittis turpis. Ut a sapien at purus aliquet vestibulum vitae eu ante. In hac habitasse platea dictumst. Ut bibendum tortor porta, posuere felis eget, ultricies magna. In et libero nec lacus dignissim mollis eget a lorem. Pellentesque quis condimentum mi. Ut at risus ipsum. Pellentesque ac mi odio. In sed magna placerat, suscipit est in, fermentum metus. Curabitur in diam ac ligula iaculis condimentum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pellentesque mollis urna, vel hendrerit nisi convallis eu. Maecenas nec urna id ligula ornare gravida non sed leo. In sit amet egestas ligula. Cras et posuere felis. Quisque metus nulla, facilisis sit amet tincidunt ac, suscipit nec ipsum. Sed vestibulum purus nisi, a blandit velit laoreet eu. Nullam volutpat dui sed nulla molestie aliquet. Nunc eleifend ut lacus id pharetra. Mauris maximus tortor sed nulla rhoncus scelerisque. Praesent dignissim purus in tincidunt convallis. Nullam convallis augue in ante bibendum, quis euismod felis sodales. Vestibulum turpis nulla, mattis ac mauris sed, pellentesque aliquet elit. Sed ornare aliquet massa, et semper magna semper vel.

Fusce nec felis ac ante iaculis tincidunt. Mauris interdum augue nec pharetra maximus. Pellentesque vel aliquam leo. Donec in ipsum eu orci facilisis gravida. Nullam consectetur lectus ut lobortis facilisis. Aenean at pharetra lorem. In luctus ante tortor, ut condimentum ipsum malesuada ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt, erat vitae mollis elementum, tellus sapien cursus diam, et dignissim magna velit eget mi. Nam leo justo, semper in quam id, ullamcorper dictum massa.

Donec consequat tempor suscipit. Aliquam convallis eros vehicula, volutpat risus eget, porta massa. Suspendisse potenti. Mauris finibus pellentesque purus, eu efficitur tortor accumsan bibendum. Phasellus rutrum, dolor ac cursus aliquet, velit velit blandit augue, ut sodales odio orci eu magna. Praesent malesuada malesuada leo, quis semper lorem pellentesque a. Aliquam erat volutpat. In mattis turpis non nisi congue iaculis. Sed fermentum ligula eu faucibus gravida. Nulla facilisi. Aenean porta accumsan sapien, vitae imperdiet orci vulputate in. Quisque ac sapien lorem. Cras risus libero, elementum ac quam nec, eleifend interdum massa. Duis pellentesque ullamcorper vehicula. Pellentesque justo quam, faucibus a felis id, commodo faucibus sem.

Vivamus ante nulla, maximus sed finibus ac, mollis nec diam. Quisque placerat enim ante, vel ullamcorper risus tempus at. Etiam quis est sed erat rutrum lobortis. Aliquam eu varius mauris. Cras ac convallis purus. Praesent sit amet leo vitae lorem fringilla sodales. Proin sit amet nunc feugiat, iaculis est sed, molestie arcu. Maecenas feugiat urna sit amet tincidunt scelerisque. Pellentesque ultricies erat sed turpis congue, vel porta massa sagittis. Vivamus non accumsan odio. Vivamus ipsum dui, luctus id mauris vitae, semper pellentesque tortor. Aliquam erat volutpat. Proin vitae auctor mauris. Donec dapibus odio euismod, dignissim nisl nec, tristique dui.

Fusce nec sapien quis nibh lobortis lobortis at vitae nulla. Sed mollis mauris in lacus porttitor elementum sed nec orci. Mauris quis dolor at ex placerat placerat. Vivamus tincidunt sagittis turpis. Ut a sapien at purus aliquet vestibulum vitae eu ante. In hac habitasse platea dictumst. Ut bibendum tortor porta, posuere felis eget, ultricies magna. In et libero nec lacus dignissim mollis eget a lorem. Pellentesque quis condimentum mi. Ut at risus ipsum. Pellentesque ac mi odio. In sed magna placerat, suscipit est in, fermentum metus. Curabitur in diam ac ligula iaculis condimentum.</p>
  </div>
    )
;
